version = 0.1

[default.deploy.parameters]
stack_name = "zoolanding-config-runtime-read"
resolve_s3 = true
s3_prefix = "zoolanding-config-runtime-read"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "ConfigTableName=zoolanding-config-registry",
  "ConfigPayloadsBucketName=zoolanding-config-payloads",
  "ContentHubMetadataTableName=zoolanding-content-hub-prod-ContentHubMetadataTable-IQ1WMU24XMPB",
  "ContentHubMetadataTableNameTest=zoolanding-content-hub-test-ContentHubMetadataTable-ZV7P652CS11F",
  "ContentHubMetadataTableNameProd=zoolanding-content-hub-prod-ContentHubMetadataTable-IQ1WMU24XMPB",
  "ContentHubPackagesBucketName=zoolanding-content-hub-pr-contenthubpackagesbucket-ujejm7mr5unu",
  "ContentHubPackagesBucketNameTest=zoolanding-content-hub-te-contenthubpackagesbucket-gdgtasj0yb0o",
  "ContentHubPackagesBucketNameProd=zoolanding-content-hub-pr-contenthubpackagesbucket-ujejm7mr5unu",
  "RuntimeExecutionBoundaryArn=arn:aws:iam::765932874577:policy/zoolanding-config-runtime-read-production-execution-boundary",
  "LogLevel=INFO"
]

[test.deploy.parameters]
stack_name = "zoolanding-config-runtime-read-test"
resolve_s3 = true
s3_prefix = "zoolanding-config-runtime-read-test"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvironmentName=test",
  "ConfigTableName=zoolanding-config-registry-test",
  "ConfigPayloadsBucketName=zoolanding-config-payloads-test",
  "ContentHubMetadataTableName=zoolanding-content-hub-test-ContentHubMetadataTable-ZV7P652CS11F",
  "ContentHubMetadataTableNameTest=zoolanding-content-hub-test-ContentHubMetadataTable-ZV7P652CS11F",
  "ContentHubMetadataTableNameProd=zoolanding-content-hub-prod-ContentHubMetadataTable-IQ1WMU24XMPB",
  "ContentHubPackagesBucketName=zoolanding-content-hub-te-contenthubpackagesbucket-gdgtasj0yb0o",
  "ContentHubPackagesBucketNameTest=zoolanding-content-hub-te-contenthubpackagesbucket-gdgtasj0yb0o",
  "ContentHubPackagesBucketNameProd=zoolanding-content-hub-pr-contenthubpackagesbucket-ujejm7mr5unu",
  "RuntimeExecutionBoundaryArn=arn:aws:iam::765932874577:policy/zoolanding-config-runtime-read-test-execution-boundary",
  "LogLevel=INFO"
]

[prod.deploy.parameters]
stack_name = "zoolanding-config-runtime-read"
resolve_s3 = true
s3_prefix = "zoolanding-config-runtime-read"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "EnvironmentName=prod",
  "ConfigTableName=zoolanding-config-registry",
  "ConfigPayloadsBucketName=zoolanding-config-payloads",
  "ContentHubMetadataTableName=zoolanding-content-hub-prod-ContentHubMetadataTable-IQ1WMU24XMPB",
  "ContentHubMetadataTableNameTest=zoolanding-content-hub-test-ContentHubMetadataTable-ZV7P652CS11F",
  "ContentHubMetadataTableNameProd=zoolanding-content-hub-prod-ContentHubMetadataTable-IQ1WMU24XMPB",
  "ContentHubPackagesBucketName=zoolanding-content-hub-pr-contenthubpackagesbucket-ujejm7mr5unu",
  "ContentHubPackagesBucketNameTest=zoolanding-content-hub-te-contenthubpackagesbucket-gdgtasj0yb0o",
  "ContentHubPackagesBucketNameProd=zoolanding-content-hub-pr-contenthubpackagesbucket-ujejm7mr5unu",
  "RuntimeExecutionBoundaryArn=arn:aws:iam::765932874577:policy/zoolanding-config-runtime-read-production-execution-boundary",
  "LogLevel=INFO"
]
