version = 0.1

[default.deploy.parameters]
stack_name = "zoolanding-config-runtime-read"
resolve_s3 = true
s3_prefix = "zoolanding-config-runtime-read"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "ConfigTableName=zoolanding-config-registry",
  "ConfigPayloadsBucketName=zoolanding-config-payloads",
  "LogLevel=INFO"
]
